expname: "test"

temp:
  target_dir: "/haoyu/data/ToyADMOS2_clean"
  task: "ToyTrain" # "ToyTrain" "ToyCar"
  nfft: 512
  AMINO_DIR: "../../.."

datamodule:
  datasets:
    train:
      select: "AMINO.datamodule.datasets:TOYADMOS2_DATASET"
      conf:
        path: ${temp.target_dir}/${temp.task}/train
    val:
      select: "AMINO.datamodule.datasets:TOYADMOS2_DATASET"
      conf:
        path: ${temp.target_dir}/${temp.task}/source_test
    test: null
    # test: 
    #   select: "AMINO.datamodule.datasets:TOYADMOS2_DATASET"
    #   conf:
    #     path: ${temp.target_dir}/${temp.task}/target_test
  after_transform:
    train:
      - select: "AMINO.datamodule.preprocess:FFT"
        conf:
          n_fft: ${temp.nfft}
    val:
      - select: "AMINO.datamodule.preprocess:FFT"
        conf:
          n_fft: ${temp.nfft}
    test:
      - select: "AMINO.datamodule.preprocess:FFT"
        conf:
          n_fft: ${temp.nfft}
  dataloaders:
    train:
      batch_size: 2
    val:
      batch_size: 2

module:
  select: "AMINO.modules.autoencoder:AMINO_AUTOENCODER"
  conf:
    net_conf:
      conf:
        feature_dim: '${nfft2fea_dim: ${temp.nfft}}' 
        # nfft2fea_dim could automatically transfer temp.nfft into (temp.nfft /2 + 1)

trainer:
  gpus:
    - 0