variables:
  target_dir: "/haoyu/data/ToyADMOS2_clean"
  task: "ToyTrain" # "ToyTrain" "ToyCar"
  nfft: 512
  AMINO_DIR: "../../.."
  batch_size: 256
  dataloaders_num_workers: 5

datamodule:
  datasets:
    train:
      select: "AMINO.datamodule.datasets:TOYADMOS2_DATASET"
      conf:
        path: ${variables.target_dir}/${variables.task}/train
    val:
      select: "AMINO.datamodule.datasets:TOYADMOS2_DATASET"
      conf:
        path: ${variables.target_dir}/${variables.task}/source_test
    test: null
    # test: 
    #   select: "AMINO.datamodule.datasets:TOYADMOS2_DATASET"
    #   conf:
    #     path: ${variables.target_dir}/${variables.task}/target_test
  after_transform:
    train:
      - select: "AMINO.datamodule.preprocess:MelSpectrogram"
        conf:
          n_fft: ${variables.nfft}
    val:
      - select: "AMINO.datamodule.preprocess:MelSpectrogram"
        conf:
          n_fft: ${variables.nfft}
    test:
      - select: "AMINO.datamodule.preprocess:MelSpectrogram"
        conf:
          n_fft: ${variables.nfft}
  dataloaders:
    train:
      # auto_scale_batch_size 'power' in V100 16G: 1516. might to large
      batch_size: ${variables.batch_size}
      num_workers: ${variables.dataloaders_num_workers}
    val:
      batch_size: ${variables.batch_size}
      num_workers: ${variables.dataloaders_num_workers}

module:
  select: "AMINO.modules.autoencoder:AMINO_AUTOENCODER"
  conf:
    net_conf:
      conf:
        feature_dim: '${nfft2fea_dim: ${variables.nfft}}' 
        # nfft2fea_dim could automatically transfer temp.nfft into (temp.nfft /2 + 1)

trainer:
  gpus:
    - 0
  auto_scale_batch_size: null
  log_every_n_steps: 1

loggers:
  tensorboard: true
  wandb: true

hydra:
  run:
    dir: exp/${now:%Y-%m-%d}/${now:%H-%M-%S}